# Form implementation generated from reading ui file 'gui/GUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_packet_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_packet_button.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.add_packet_button.setCheckable(True)
        self.add_packet_button.setObjectName("add_packet_button")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 10, 160, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.packetlay = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.packetlay.setContentsMargins(0, 0, 0, 0)
        self.packetlay.setObjectName("packetlay")
        self.remove_packet_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_packet_button.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.remove_packet_button.setObjectName("remove_packet_button")
        self.s_status = QtWidgets.QLabel(self.centralwidget)
        self.s_status.setGeometry(QtCore.QRect(20, 90, 47, 13))
        self.s_status.setObjectName("s_status")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_packet_button.setText(_translate("MainWindow", "add packet"))
        self.remove_packet_button.setText(_translate("MainWindow", "remove packet"))
        self.s_status.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
