# Form implementation generated from reading ui file '.\GUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(292, 436)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_filter_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_filter_button.setGeometry(QtCore.QRect(10, 30, 75, 23))
        self.add_filter_button.setCheckable(True)
        self.add_filter_button.setObjectName("add_filter_button")
        self.remove_filter_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_filter_button.setGeometry(QtCore.QRect(10, 60, 75, 23))
        self.remove_filter_button.setObjectName("remove_filter_button")
        self.s_status = QtWidgets.QLabel(self.centralwidget)
        self.s_status.setGeometry(QtCore.QRect(20, 110, 47, 13))
        self.s_status.setObjectName("s_status")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(110, 10, 151, 141))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 149, 139))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 151, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.filter_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.filter_layout.setContentsMargins(0, 0, 0, 0)
        self.filter_layout.setObjectName("filter_layout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.filter_layout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 292, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_filter_button.setText(_translate("MainWindow", "add filter"))
        self.remove_filter_button.setText(_translate("MainWindow", "remove filter"))
        self.s_status.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
